### ISSUE TITLE
Cloud issue

### ISSUE THREAD

**Issue by cstriage13** [armory3d/armortools#1231] opened 2021-12-30 21:53 UTC
I am unable to use the cloud nothing will load up it just stays blank but titles are there. 

*ArmorPaint 0.9-b5969f4, Windows*

**Issue description:**
I am unable to use the cloud nothing will load up it just stays blank but titles are there. 
**Steps to reproduce:**
All you have to do is open the browser and try to use. Other than that I have not changed any of the code, etc. 
![cloud](https://user-images.githubusercontent.com/84180614/147790350-3f6137ef-15c8-4b65-be68-eaab3dcf6b7c.png)

**Comment by ikonnow** [comment] 2022-01-11 10:08
The same error happened to me, I was able to solve it by leaving the program in the built folder /build/krom. There the icons are displayed without any problems. Probably an permission issue / or similar.

**Comment by MathemanFlo** [comment] 2022-02-24 06:01
I guess you copied the krom directory with all its subdirectories to a new location, didn't you? This should work savely and only give you issues if you copy it to a directory ArmorPaint has no write permissions, e.g. the program files directories. The reson is ArmorPaint downloads the materials, textures, ... from the cloud and saves the in a child directory.

**Comment by adamscott** [comment] 2022-03-23 14:08
This seems to be a duplicate of #1199

**Comment by YAFU** [comment] 2022-04-21 19:34
> The same error happened to me, I was able to solve it by leaving the program in the build folder /build/krom. Executing it there the icons are displayed without any problems. Probably an permission issue / or similar.

Thanks, that worked. I have copied "ArmorPaint" executable from "/armorpaint/armorcore/Deployment/" to "/armorpaint/build/krom/" and running it from there with "./ArmorPaint ../../build/krom" and now I can use Cloud without the entire program freezing.

I clarify that I had the problem using default locations without having moved krom folder or anything like that.

**Comment by Menotdan** [comment] 2023-04-15 20:40
Same thing happened to me, ikon's solution worked. I hope they fix this at some point

**Comment by CaroRed** [comment] 2024-01-10 13:00
I had the same issue. I copy the versión from the Release folder to /armorpaint/build/krom/ but there was an executable file there So replaced it.
I open the program again and now it loads the materials but when you apply the materials it takes some times like the program freeze a while. Also when you open a materials folder the first time.

**Comment by luboslenco** [comment] 2024-01-28 10:11
Linking with https://github.com/armory3d/armortools/issues/1668, thanks for all the details.

**Closed by luboslenco** 2024-01-28 10:11 UTC
Labels: bug

**Comment by Ceemester** [comment] 2024-02-19 19:56
I think I've found a manual fix for this issue.

1. Close ArmorPaint.
2. Navigate to ArmorPaint/cloud
3. You should see a file named materials. Delete that file.
4. Create a folder named materials in ArmorPaint/cloud
5. Start ArmorPaint. The Cloud browser should now be able to browse and download all materials.
