### ISSUE TITLE
Support for 3DConnexion controllers

### ISSUE THREAD

**Issue by santiagopm** [armory3d/armortools#1703] opened 2024-04-07 16:35 UTC
*ArmorPaint 1.0 alpha-6246a99, Windows*

**Feature description:**

Add support for 3DConnexion controllers

**Comment by moolight-seashell** [comment] 2024-05-29 11:31
duplicate of https://github.com/armory3d/armortools/issues/1658

**Comment by luboslenco** [comment] 2024-09-01 21:15
Link with https://github.com/armory3d/armortools/issues/1658.

**Closed by luboslenco** 2024-09-01 21:15 UTC
Labels: feature request
