### ISSUE TITLE
Force close on iPad

### ISSUE THREAD

**Issue by Masterkopet** [armory3d/armortools#1494] opened 2023-01-04 12:51 UTC
*ArmorPaint 0.9-8bd04fa, iPad-BFEE9CF4-3C3A-4DA7-ADED-3A3B668DC8E1

force close when i use around 3-5 minutes, then blank screen or force close
![2A992F5C-DD31-4FE0-8B92-2876135EAFCB](https://user-images.githubusercontent.com/121948199/210558919-bf2dd473-0edf-40ea-ab1d-9fac1c72ab97.png)

**Comment by luboslenco** [comment] 2023-01-06 14:04
Thanks for report - which iPad model are you on?

**Comment by Masterkopet** [comment] 2023-01-06 14:19
Thank you for fast respond, my device iPad Pro M1, iPadOS 16.2. 

Problem happened when i use AP 3-5 min, then freeze and force close.

**Comment by luboslenco** [comment] 2023-07-28 13:36
Hey, can you please test with the latest update? Do you still get the same issue?

**Comment by Masterkopet** [comment] 2023-07-29 16:20
> Hey, can you please test with the latest update? Do you still get the same issue?

Hi! I’ve test with latest update and I have no issue, im using M1 iPadOS 17, it can also working with 4k layers and export 4k. Thanks alot @luboslenco

**Comment by Calinou** [comment] 2023-09-01 23:19
@Masterkopet Since the issue is resolved on your end, you can close this issue :slightly_smiling_face:

**Closed** 2023-09-02 08:07 UTC
Labels: bug
